name = "lune_utils/nobloxluau"
version = "0.1.0"
description = "A Luau API wrapper for Roblox."
authors = ["0xJWLabs <hi@0xjwlabs.dev>"]
repository = "https://github.com/lune-utils/noblox.luau"
license = "MIT"
private = true

[engines]
lune = "^0.9.4"

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
roxios = { repo = "https://github.com/lune-utils/roxios.git", rev = "4aaaa56" }
